name: pyhpda
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - numpy
  - scipy
  - pandas
  - cython
  - numba
  - cudatoolkit
  - cupy
  - h5py
  - hdf5
  - netcdf4 
  - matplotlib
  - dask
  - ipywidgets
  - widgetsnbextension 
  - dask-jobqueue
  - dask-labextension   
  - snakemake-minimal
  - ipyparallel
  - xarray
  - jupyter
  - jupyterlab
  - pip
  - pip:
    - line_profiler
    